package com.fullstorydev.shoppedemo.adapters;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;

import androidx.annotation.NonNull;
import androidx.databinding.DataBindingUtil;
import androidx.recyclerview.widget.RecyclerView;

import com.fullstory.FS;
import com.fullstorydev.shoppedemo.R;
import com.fullstorydev.shoppedemo.data.Item;
import com.fullstorydev.shoppedemo.databinding.ListItemCartBinding;
import com.fullstorydev.shoppedemo.ui.cart.CartEventHandlers;

import java.util.ArrayList;
import java.util.List;

public class CartItemAdapter extends RecyclerView.Adapter<CartItemAdapter.CartItemViewHolder> {
    private List<Item> mItemList;
    private LayoutInflater layoutInflater;
    private CartEventHandlers mCartHandlers;

    public CartItemAdapter(CartEventHandlers cartHandlers) {
        mCartHandlers = cartHandlers;
        mItemList = new ArrayList<>();
    }

    @NonNull
    @Override
    public CartItemAdapter.CartItemViewHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
        if (layoutInflater == null) {
            layoutInflater = LayoutInflater.from(parent.getContext());
        }
        // binding class automatically generated by Data Binding Library from list_item_cart
        ListItemCartBinding binding = DataBindingUtil.inflate(layoutInflater, R.layout.list_item_cart, parent, false);
        return new CartItemAdapter.CartItemViewHolder(binding);
    }

    @Override
    public void onBindViewHolder(@NonNull CartItemAdapter.CartItemViewHolder holder, int position) {
        holder.bind(mItemList.get(position));
    }

    @Override
    public int getItemCount() {
        if(mItemList == null) return 0;
        return mItemList.size();
    }

    public void setItemList(List<Item> items){
        //TODO: check diff and use callback & DiffUtil.DiffResult to avoid recreating every view
        mItemList = items;
        notifyDataSetChanged();
    }

    class CartItemViewHolder extends RecyclerView.ViewHolder implements View.OnClickListener {
        private ListItemCartBinding binding;
        CartItemViewHolder(@NonNull ListItemCartBinding binding){
            super(binding.getRoot());
            this.binding = binding;
            // bind the on click handler for add to cart buttons
            this.binding.setHandlers(mCartHandlers);
        }

        void bind(Item item) {
            binding.setItem(item);
            binding.executePendingBindings();
        }

        @Override
        public void onClick(View v) {
            // getting clicked item from adapter position
            Item item = mItemList.get(getAdapterPosition());
            try {
                //TODO: When recyclerview is clicked, get the item and perform action here, i.e. show item details fragment
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }
}
